export const PERMISSIONS = {
  // Patients
  PATIENTS_VIEW: 'patients:view',
  PATIENTS_CREATE: 'patients:create',
  PATIENTS_EDIT: 'patients:edit',
  PATIENTS_DELETE: 'patients:delete',
  PATIENTS_EXPORT: 'patients:export',
  PATIENTS_IMPORT: 'patients:import',
  PATIENTS_MERGE: 'patients:merge',

  // Appointments
  APPOINTMENTS_VIEW: 'appointments:view',
  APPOINTMENTS_CREATE: 'appointments:create',
  APPOINTMENTS_EDIT: 'appointments:edit',
  APPOINTMENTS_DELETE: 'appointments:delete',
  APPOINTMENTS_CONFIRM: 'appointments:confirm',

  // Queue
  QUEUE_VIEW: 'queue:view',
  QUEUE_MANAGE: 'queue:manage',

  // EMR
  EMR_VIEW: 'emr:view',
  EMR_CREATE: 'emr:create',
  EMR_EDIT: 'emr:edit',
  EMR_SIGN: 'emr:sign',
  EMR_AMEND: 'emr:amend',

  // Billing
  BILLING_VIEW: 'billing:view',
  BILLING_CREATE: 'billing:create',
  BILLING_REFUND: 'billing:refund',
  BILLING_EXPENSES: 'billing:expenses',
  BILLING_CASH_REGISTER: 'billing:cash_register',

  // Reports
  REPORTS_VIEW: 'reports:view',
  REPORTS_FINANCIAL: 'reports:financial',
  REPORTS_EXPORT: 'reports:export',

  // Staff
  STAFF_VIEW: 'staff:view',
  STAFF_MANAGE: 'staff:manage',
  STAFF_BLOCK: 'staff:block',

  // Branches
  BRANCHES_VIEW: 'branches:view',
  BRANCHES_MANAGE: 'branches:manage',

  // Inventory
  INVENTORY_VIEW: 'inventory:view',
  INVENTORY_MANAGE: 'inventory:manage',

  // Insurance
  INSURANCE_VIEW: 'insurance:view',
  INSURANCE_MANAGE: 'insurance:manage',

  // Payroll
  PAYROLL_VIEW: 'payroll:view',
  PAYROLL_MANAGE: 'payroll:manage',

  // Marketing
  MARKETING_VIEW: 'marketing:view',
  MARKETING_MANAGE: 'marketing:manage',

  // System
  SYSTEM_SETTINGS: 'system:settings',
  SYSTEM_LOGS: 'system:logs',
  SYSTEM_BACKUP: 'system:backup',
  SYSTEM_MONITORING: 'system:monitoring',

  // Audit
  AUDIT_VIEW: 'audit:view',

  // Documents
  DOCUMENTS_VIEW: 'documents:view',
  DOCUMENTS_CREATE: 'documents:create',
  DOCUMENTS_DELETE: 'documents:delete',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Default permission sets for built-in roles
export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  owner: Object.values(PERMISSIONS),
  sysadmin: Object.values(PERMISSIONS),
  chief_doctor: [
    PERMISSIONS.PATIENTS_VIEW, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_EDIT,
    PERMISSIONS.APPOINTMENTS_VIEW, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_EDIT, PERMISSIONS.APPOINTMENTS_CONFIRM,
    PERMISSIONS.QUEUE_VIEW, PERMISSIONS.QUEUE_MANAGE,
    PERMISSIONS.EMR_VIEW, PERMISSIONS.EMR_CREATE, PERMISSIONS.EMR_EDIT, PERMISSIONS.EMR_SIGN, PERMISSIONS.EMR_AMEND,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_FINANCIAL,
    PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_CREATE,
  ],
  doctor: [
    PERMISSIONS.PATIENTS_VIEW, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_EDIT,
    PERMISSIONS.APPOINTMENTS_VIEW, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_EDIT,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.EMR_VIEW, PERMISSIONS.EMR_CREATE, PERMISSIONS.EMR_EDIT, PERMISSIONS.EMR_SIGN,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_CREATE,
  ],
  admin: [
    PERMISSIONS.PATIENTS_VIEW, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_EDIT, PERMISSIONS.PATIENTS_EXPORT, PERMISSIONS.PATIENTS_IMPORT,
    PERMISSIONS.APPOINTMENTS_VIEW, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_EDIT, PERMISSIONS.APPOINTMENTS_DELETE, PERMISSIONS.APPOINTMENTS_CONFIRM,
    PERMISSIONS.QUEUE_VIEW, PERMISSIONS.QUEUE_MANAGE,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_REFUND, PERMISSIONS.BILLING_EXPENSES, PERMISSIONS.BILLING_CASH_REGISTER,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.INSURANCE_VIEW, PERMISSIONS.INSURANCE_MANAGE,
    PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_CREATE, PERMISSIONS.DOCUMENTS_DELETE,
  ],
  nurse: [
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.EMR_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
  ],
  accountant: [
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_REFUND, PERMISSIONS.BILLING_EXPENSES, PERMISSIONS.BILLING_CASH_REGISTER,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_FINANCIAL, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.INSURANCE_VIEW, PERMISSIONS.INSURANCE_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
  ],
  patient: [
    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
  ],
};
